#!/usr/bin/env sh

set -e

BASE_DIR=$(dirname "$0")/..
SCRIPTS_DIR="$BASE_DIR/scripts"
CACHE_DIR="$BASE_DIR/cache"
CONFIG_DIR="$BASE_DIR/config"
DOWNLOADS_DIR="$CACHE_DIR/downloads"
LOCAL_FILES_DIR="$CONFIG_DIR/files"
mkdir -p "$DOWNLOADS_DIR"

DOWNLOADER_PATH="$SCRIPTS_DIR/downloader"
SERVER_PATH="$SCRIPTS_DIR/server"

DOWNLOADS_LIST_PATH="$CONFIG_DIR/downloads.list"

"$DOWNLOADER_PATH" -d "$DOWNLOADS_DIR" -l "$LOCAL_FILES_DIR" "$DOWNLOADS_LIST_PATH"
"$SERVER_PATH" "$DOWNLOADS_DIR" &
SERVER_PID_PATH=$!

lb build noauto "${@}" 2>&1 | tee build.log

kill "$SERVER_PID_PATH"
